name: 'GraphQL Diff'
description: 'A neat summary of the changes you made to your GraphQL schema.'
branding: 
  icon: 'columns'
  color: 'purple'
inputs:
  token:
    description: 'GitHub token to post the comment'
    required: true
  old-schema: 
    description: 'Old schema location'
    required: true
  new-schema:
    description: 'New schema location'
    required: true
runs:
  using: 'node12'
  main: 'index.js'